on:
  fork:
  push:
    branches: [ main ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>It''s great having you contribute to this project</h1> '
          pr-message: |
            👋 Hello @${{ github.actor }}, thank you for submitting a pull request and making Pridebot even better!  🚀 To allow your work to be merged as quickly as possible, we advise you to:
            - Verify your PR is up-to-date with ``tyffical/main``. If your PR is behind ``tyffical/main`` update by running ``git merge tyffical/main`` on your local Git command line.
            - Ensure all of your commit messages as well as your pull request name begin with one of our approved prefixes: ``feat``, ``fix``, ``docs``, ``style``, ``refactor``, ``test``, or ``chore``. This will help us keep our git commit log clean.
            - Join our Discord server at https://blahaj.lol/discord to keep up with the bot's development! :shark:
            - :shark: Make sure to have fun! We want BLAHAJGang to be a safe and welcoming (and memey) environment for all! :shark:
            Have a BLAHAJ-tastic day! :shark:
